### PR TITLE
Added the homepage for FurryFeet

### PR DESCRIPTION
**Pull request by milkovskamarija**
Latest changes look like this:
image

### CODE REVIEW

**Comment by SaraMisajlovska** [comment]
Please include a screenshot if you can

**Comment by milkovskamarija** [comment]
Screenshot_1

**Comment by milkovskamarija** [comment]
Opinions are welcome

Screenshot_1

**Comment by vitruvianarendt** [comment]
Since the header and footer are designed, they should automatically appear on every page, please check if there's an issue, or if they appear please add a screenshot with them included.

**Comment by StankovskiA** [comment]
Latest changes look like this:
image

**Review by vitruvianarendt — APPROVED** [review]

**Review by StankovskiA — APPROVED** [review]

**Pull request merged**
