### PR TITLE
about page added

### PR DESCRIPTION
**Pull request by terezag07**
about_page

### CODE REVIEW

**Comment by vitruvianarendt** [comment]
Align the texts vertically and centre the images, also please add a little bit of padding on top of the images.

**Comment by terezag07** [comment]
> Align the texts vertically and centre the images, also please add a little bit of padding on top of the images.

image

**Review by vitruvianarendt — APPROVED** [review]
Looks great!

**Review by MuratUseini123 — APPROVED** [review]
well done

**Pull request merged**
